# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '/'
    weight: 10
  - name: Course
    weight: 20
    identifier: courses
  - name: Week 1 - Intro to R & RStudio
    PageRef: course/Week 1 - Introduction to R & Rstudio/_index.md
    weight: 10
    parent: courses
  - name: Week 2 - Narrative writing in R
    PageRef: course/Week 2 - Narrative writing in R/_index.md
    weight: 20
    parent: courses
  - name: Week 3 - Descriptive Statistics 101
    PageRef: course/Week 3 - Descriptive Statistics 101/_index.md
    weight: 30
    parent: courses
  - name: Week 4 - Inferential Statistics 101
    PageRef: course/Week 4 - Inferential Statistics 101/_index.md
    weight: 40
    parent: courses
  - name: Week 5 - The grammar of graphics, Pt.1
    PageRef: course/Week 5 - The grammar of graphics, Pt.1/_index.md
    weight: 50
    parent: courses
  - name: Week 6 - The grammar of graphics, Pt.2
    PageRef: course/Week 6 - The grammar of graphics, Pt.2/_index.md
    weight: 60
    parent: courses
  - name: Week 7 - Essay writing skill & Mini Report
    PageRef: course/Week 7 - Essay writing skill & Mini Report/_index.md
    weight: 70
    parent: courses
  - name: Week 8 - Assignment Troubleshooting
    PageRef: course/Week 8 - Assignment Troubleshooting/_index.md
    weight: 80
    parent: courses
  - name: Resources
    url: '/Resources'
    weight: 85
    
